name: Go

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: 
    steps:
    - name: Load repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.1

    - name: Build client
      run: make -f Makefile.client

    - name: Build server
      run: make -f Makefile.server

    - name: Upload release assets
      uses: alexellis/upload-assets@0.3.0
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        asset_paths: '["./build/*"]'
